### PR TITLE
[Chore: #163861498] Setup Image Upload with cloudinary

### PR DESCRIPTION
**Pull request by ebenezerdon**
#### What does this PR do?
- This PR sets up Image Upload with Cloudinary

#### Description of Task to be completed?
 - Set up Cloudinary for image upload

#### What are the relevant pivotal tracker stories?
- [#163861498](https://www.pivotaltracker.com/story/show/163861498)

### CODE REVIEW

**Review by rajeman — APPROVED** [review]

**Comment by habibaudu** [comment]
@ebenezerdon  Our tests dropped by -7.5%. Please Can I Know why?

**Comment by ebenezerdon** [comment]
I didn't notice earlier. The function is not being used yet so I didn't consider testing for it.

**Comment by habibaudu** [comment]
> I didn't notice earlier. The function is not being used yet so I didn't consider testing for it.

Ok.

**Comment by andela-mabdussalam** [comment]
@ebenezerdon Add tests.

**Comment by ebenezerdon** [comment]
Okay, I'll do that.

**Review by andela-mabdussalam — APPROVED** [review]

**Pull request merged**
