### PR TITLE
[Feature: #164217377]Add created article to redux store

### PR DESCRIPTION
**Pull request by rajeman**
#### What does this PR do?
- It ensures newly created articles are added to the redux store

#### Description of Task to be completed?
- [x] Dispatch an action to add newly created articles to store
- [x] Write unit tests

#### How should this be manually tested?
- goto `/create-article` and create an article
- navigate to the category of the newly created article and it should appear without api call if there were existing articles in store before it was created

#### What are the relevant pivotal tracker stories?
- [#164217377](https://www.pivotaltracker.com/story/show/164217377)

### CODE REVIEW

**Comment by andela-mabdussalam** [comment]
@rajeman You should be able to test that actions are dispatched.

See missed lines.

https://coveralls.io/builds/21865573/source?filename=src%2Fapp%2Farticle%2Fduck%2Foperations.js#L46

**Comment by rajeman** [comment]
I will do that now

**Comment by rajeman** [comment]
I have covered the lines

**Comment by rajeman** [comment]
> I have covered the lines

Those lines are covered on my branch. I don't know why the coverage drops on coverall after some minutes.

**Review by andela-mabdussalam — APPROVED** [review]

**Pull request merged**
